### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [saucedacity/saucedacity#10]
can saucedacity be translated ?

**Comment by generic-pers0n** [comment]
Totally...except I lack knowledge of any other languages. If you can translate, however, feel free to! I (really) welcome it!

**Comment by mondlicht-und-sterne** [comment]
@generic-pers0n 
that looks difficult :-/ 
otherwise i translate almost everything on weblate i have translated almost 14000 strings since july 2020.
many languages would not be a problem, but the question is how to do it.

**Comment by generic-pers0n** [comment]
@mondlicht-und-sterne That's impressive...

Well, I'll see if I can make a wiki page about translating Saucedacity. I'll be taking information from the previously mentioned links, but I'll see if I can make some tutorial or something. Let's see what we can do...

**Comment by fitojb** [comment]
It'd be good to merge Tenacity's translations in here.

I was hurt that I spent my time translating that project for nothing.

**Comment by generic-pers0n** [comment]
> It'd be good to merge Tenacity's translations in here.
> 
> I was hurt that I spent my time translating that project for nothing.

Sounds like a good idea!
