### ISSUE TITLE
its alive

### ISSUE THREAD

**Issue by Reaper10** [saucedacity/saucedacity#71]
Hi love this zombie. I hope it keeps limping on 
I've been on the Tenacity code base [here](https://github.com/tenacityteam/tenacity/issues/created_by/Reaper10). I'm not going bother you im not coder so sorry

**Comment by n0toose** [comment]
Hey @Reaper10, I'd just like to politely remind you that GitHub's Issues are not a place for casual discussion and that our Matrix channels would be more appropriate for this.

(P.S. Thanks for all of your bug reports and efforts and I'm sorry that we couldn't get around to it, you haven't gone unnoticed.)
