### ISSUE TITLE
questions about building on windows.

### ISSUE THREAD

**Issue by Rossmaxx** [saucedacity/saucedacity#84]
I am trying to build saucedacity on windows before i start working on some code. I have some doubts related to building it on windows: 
- i have vcpkg preconfigured and do use it to build stuff occasionally. Is it possible to use local version of vcpkg instead of the submodule? if yes, what should i pass to the command line and what dependencies should i get before building?

**Comment by Rossmaxx** [comment]
the issue got duplicated

**Comment by poyribn** [comment]
original issue: https://github.com/tenacityteam/saucedacity/issues/83
